# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQdjDK_dMDSVOAQP6_f0VZFPj2T01Ggj
"""

import pandas as pd

def analyze_csv(file):
    df = pd.read_csv(file)

    print("\n===== DATA PREVIEW ===telek======")
    print(df.head())

    print("\n===== BASIC INFO ====")
    df.info()

    print("\n===== STATISTICAL SUMMARY ====")
    print(df.describe())

    print("\n===== MEAN ====")
    print(df.mean(numeric_only=True))

    print("\n===== MEDIAN ====")
    print(df.median(numeric_only=True))

    print("\n===== MODE ====")
    print(df.mode(numeric_only=True))

    print("\n===== VARIANCE ====")
    print(df.var(numeric_only=True))

    print("\n===== STANDARD DEVIATION ====")
    print(df.std(numeric_only=True))

if __name__ == "__main__":
    file = input("Enter CSV file path: ")
    analyze_csv(file)